"""CrossHair target for api_bgp_ls_edge_update.

The entry point for test generation is
`api_bgp_ls_edge_update_with_precondition`.
"""

from modeling_primitives import opaque_addr_t, uint8_t, uint32_t
from bgp_ls.linkstate_data import *
from bgp_ls.edge_mgmt.api_bgp_ls_edge_update import BgpLsLinkState
from bgp_ls.edge_mgmt.igp_primitives import sys_id_t


def _correct_api_params(
    api_event: int,
    api_src_sys_id: int,
    api_dest_sys_id: int,
    api_local: int,
    api_remote: int,
) -> tuple[int, int, int, int, int]:
    new_src_sys_id, new_dest_sys_id, new_local, new_remote = (
        api_src_sys_id,
        api_dest_sys_id,
        api_local,
        api_remote,
    )

    # ensure sys IDs and IPs are not unspecified
    DEFAULT_ID = 1
    ALT_ID = 9552

    if new_src_sys_id == 0:
        new_src_sys_id = DEFAULT_ID

    if new_dest_sys_id == 0:
        new_dest_sys_id = ALT_ID

    if new_local == 0:
        new_local = DEFAULT_ID

    if new_remote == 0:
        new_remote = ALT_ID

    sign = lambda x: (x > 0) - (x < 0)

    # ensure edge does not point back to the same node or through the same
    # interface; we simply assign it to an adjacent hashable address
    # note that we need to ensure the new number is not zero; to do this, we
    # add the sign to move it away from zero
    if new_src_sys_id == new_dest_sys_id:
        new_dest_sys_id += sign(new_dest_sys_id)

    if new_local == new_remote:
        new_remote += sign(new_remote)

    return api_event % 5, new_src_sys_id, new_dest_sys_id, new_local, new_remote


def _correct_ted_seed(
    ted_seed: list[tuple[int, int, int, int]],
    api_src_sys_id: int,
    api_dest_sys_id: int,
    api_local: int,
    api_remote: int,
) -> list[tuple[int, int, int, int]]:

    out: list[tuple[int, int, int, int]] = []

    sys_m = {api_src_sys_id: {api_local}, api_dest_sys_id: {api_remote}}

    for edge in ted_seed:
        # skip edges with unspecified addresses
        if any(edge_id == 0 for edge_id in edge):
            continue

        src_sys_id, dest_sys_id, local, remote = edge
        edge_interfaces = ((src_sys_id, local), (dest_sys_id, remote))
        api_interfaces = (
            (api_src_sys_id, api_local),
            (api_dest_sys_id, api_remote),
        )

        # skip mismatched edges, i.e. enforce one-to-many relationship
        # between ISO sys IDs to IP addresses
        if any(
            sys_id != node and ip in ips
            for sys_id, ips in sys_m.items()
            for node, ip in edge_interfaces
        ):
            continue

        # skip edges back to the same node; doing this after mismatched edges
        # should ensure that each IP address belongs to only one uniquely
        # identifiable router
        if src_sys_id == dest_sys_id or local == remote:
            continue

        # skip edges with same node, same interface as parameters
        # this ensures that we do not need to model edge deletions at the same
        # time
        if (
            sum(
                interface == api_interface
                for interface in edge_interfaces
                for api_interface in api_interfaces
            )
            == 1
        ):
            continue

        # skip duplicates
        if any(edge == e for e in out):
            continue

        # append the valid edge
        sys_m.setdefault(src_sys_id, set()).add(local)
        sys_m.setdefault(dest_sys_id, set()).add(remote)
        out.append(edge)

        rev = (dest_sys_id, src_sys_id, remote, local)
        if rev not in out:
            out.append(rev)

    return out


def _build_state_and_api(
    ted_seed: list[tuple[int, int, int, int]],
    api_event: int,
    api_asn: int,
    api_src_sys_id: int,
    api_dest_sys_id: int,
    api_level: int,
    api_local: int,
    api_remote: int,
) -> tuple[BgpLsLinkState, BApiLinkStateUpdate]:
    """Construct the model from an empty state. API parameters are generated by
    CrossHair on the fly.
    """

    state = BgpLsLinkState(
        asn=uint32_t(api_asn),
        ted=[
            LinkStateEdge(
                uint32_t(api_asn),
                LinkStateNodeId(sys_id_t(src_sys_id), uint8_t(api_level)),
                LinkStateNodeId(sys_id_t(dest_sys_id), uint8_t(api_level)),
                opaque_addr_t(local),
                opaque_addr_t(remote),
            )
            for src_sys_id, dest_sys_id, local, remote in ted_seed
        ],
        rib=[
            BgpLsLinkNlri(
                BgpLsNode(uint32_t(api_asn), sys_id_t(src_sys_id)),
                BgpLsNode(uint32_t(api_asn), sys_id_t(dest_sys_id)),
                BgpLsLink(
                    opaque_addr_t(local),
                    opaque_addr_t(remote),
                    uint32_t(api_asn),
                ),
            )
            for src_sys_id, dest_sys_id, local, remote in ted_seed
        ],
    )

    src_node = LinkStateNodeId(sys_id_t(api_src_sys_id), uint8_t(api_level))

    attr = LinkStateAttributes(
        adv=src_node,
        name=None,
        local=opaque_addr_t(api_local),
        remote=opaque_addr_t(api_remote),
    )

    dest_node = LinkStateNodeId(sys_id_t(api_dest_sys_id), uint8_t(api_level))

    api = BApiLinkStateUpdate(
        event=BEvent(api_event), remote=dest_node, data=attr
    )
    return state, api


def api_bgp_ls_edge_update_with_precondition(
    ted_seed: list[tuple[int, int, int, int]],
    api_event: int,
    api_asn: int,
    api_src_sys_id: int,
    api_dest_sys_id: int,
    api_level: int,
    api_local: int,
    api_remote: int,
) -> BgpAttributes | None:
    api_event, api_src_sys_id, api_dest_sys_id, api_local, api_remote = (
        _correct_api_params(
            api_event, api_src_sys_id, api_dest_sys_id, api_local, api_remote
        )
    )

    ted_seed = _correct_ted_seed(
        ted_seed, api_src_sys_id, api_dest_sys_id, api_local, api_remote
    )

    state, api = _build_state_and_api(
        ted_seed,
        api_event,
        api_asn,
        api_src_sys_id,
        api_dest_sys_id,
        api_level,
        api_local,
        api_remote,
    )
    return state.api_bgp_ls_edge_update(api)
