"""CrossHair target for api_bgp_ls_edge_update.

The entry point for test generation is
`api_bgp_ls_edge_update_with_precondition`.
"""

from modeling_primitives import opaque_addr_t, uint8_t, uint32_t
from bgp_ls.edge_mgmt.api_bgp_ls_edge_update import (
    BEvent,
    BgpLsLinkState,
    BApiLinkStateUpdate,
    LinkStateAttributes,
    LinkStateEdge,
    LinkStateNodeId,
)


def _dedup_ted_seed(
    ted_seed: list[tuple[int, list[int], list[int], int, int]],
) -> list[tuple[int, list[int], list[int], int, int]]:

    out: list[tuple[int, list[int], list[int], int, int]] = []

    for edge in ted_seed:
        if any(edge == entry for entry in out):
            continue
        out.append(edge)
    return out


def _build_state_and_api(
    ted_seed: list[tuple[int, list[int], list[int], int, int]],
    api_metric: int,
    api_src_sys_id: list[int],
    api_dest_sys_id: list[int],
    api_level: int,
    api_local: int,
    api_remote: int,
) -> tuple[BgpLsLinkState, BApiLinkStateUpdate]:
    """Construct the model from an empty state. API parameters are generated by
    CrossHair on the fly.
    """

    state = BgpLsLinkState(
        ted=[
            LinkStateEdge(
                uint32_t(asn),
                LinkStateNodeId(
                    [uint8_t(b) for b in src_sys_id], uint8_t(api_level)
                ),
                LinkStateNodeId(
                    [uint8_t(b) for b in dest_sys_id], uint8_t(api_level)
                ),
                opaque_addr_t(local),
                opaque_addr_t(remote),
            )
            for asn, src_sys_id, dest_sys_id, local, remote in ted_seed
        ]
    )

    src_node = LinkStateNodeId(
        [uint8_t(b) for b in api_src_sys_id], uint8_t(api_level)
    )

    attr = LinkStateAttributes(
        valid=True,
        adv=src_node,
        name=None,
        metric=uint32_t(api_metric),
        local=opaque_addr_t(api_local),
        remote=opaque_addr_t(api_remote),
    )

    dest_node = LinkStateNodeId(
        [uint8_t(b) for b in api_dest_sys_id], uint8_t(api_level)
    )

    api = BApiLinkStateUpdate(event=BEvent.UPDATE, remote=dest_node, data=attr)
    return state, api


def api_bgp_ls_edge_update_with_precondition(
    ted_seed: list[tuple[int, list[int], list[int], int, int]],
    api_metric: int,
    api_src_sys_id: list[int],
    api_dest_sys_id: list[int],
    api_level: int,
    api_local: int,
    api_remote: int,
) -> int:
    assert len(api_src_sys_id) == 6
    assert len(api_dest_sys_id) == 6
    assert all(
        len(src_sys_id) == 6 and len(dest_sys_id) == 6
        for _, src_sys_id, dest_sys_id, _, _ in ted_seed
    )
    assert api_src_sys_id != api_dest_sys_id
    assert api_local != api_remote

    ted_seed = _dedup_ted_seed(ted_seed)
    state, api = _build_state_and_api(
        ted_seed,
        api_metric,
        api_src_sys_id,
        api_dest_sys_id,
        api_level,
        api_local,
        api_remote,
    )
    return state.api_bgp_ls_edge_update(api)
